# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator.ui'
#
# Created: Thu Oct 02 20:45:04 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 715)
        MainWindow.setMinimumSize(QtCore.QSize(900, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.textEdit = QtGui.QTextEdit(self.splitter)
        self.textEdit.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit.setTabStopWidth(40)
        self.textEdit.setObjectName("textEdit")
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setMinimumSize(QtCore.QSize(325, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitterHB = QtGui.QSplitter(self.widget)
        self.splitterHB.setOrientation(QtCore.Qt.Vertical)
        self.splitterHB.setHandleWidth(10)
        self.splitterHB.setObjectName("splitterHB")
        self.widgetGLContainer = QtGui.QWidget(self.splitterHB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetGLContainer.sizePolicy().hasHeightForWidth())
        self.widgetGLContainer.setSizePolicy(sizePolicy)
        self.widgetGLContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetGLContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetGLContainer.setObjectName("widgetGLContainer")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widgetGLContainer)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(self.splitterHB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPupitre = QtGui.QWidget()
        self.tabPupitre.setObjectName("tabPupitre")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.tabPupitre)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.tabWidget2 = QtGui.QTabWidget(self.tabPupitre)
        self.tabWidget2.setMinimumSize(QtCore.QSize(200, 0))
        self.tabWidget2.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget2.setFont(font)
        self.tabWidget2.setObjectName("tabWidget2")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout = QtGui.QGridLayout(self.tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetButtonContainer = QtGui.QWidget(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetButtonContainer.sizePolicy().hasHeightForWidth())
        self.widgetButtonContainer.setSizePolicy(sizePolicy)
        self.widgetButtonContainer.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.widgetButtonContainer.setObjectName("widgetButtonContainer")
        self.gridLayout_2 = QtGui.QGridLayout(self.widgetButtonContainer)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.widgetButtonContainer)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButtonBicepsG = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonBicepsG.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonBicepsG.setObjectName("pushButtonBicepsG")
        self.gridLayout_2.addWidget(self.pushButtonBicepsG, 4, 0, 1, 1)
        self.pushButtonBicepsD = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonBicepsD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonBicepsD.setObjectName("pushButtonBicepsD")
        self.gridLayout_2.addWidget(self.pushButtonBicepsD, 4, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSliderBicepsG0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderBicepsG0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderBicepsG0.setMinimum(0)
        self.horizontalSliderBicepsG0.setMaximum(100)
        self.horizontalSliderBicepsG0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBicepsG0.setObjectName("horizontalSliderBicepsG0")
        self.horizontalLayout.addWidget(self.horizontalSliderBicepsG0)
        self.horizontalSliderBicepsG2 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderBicepsG2.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderBicepsG2.setMinimum(0)
        self.horizontalSliderBicepsG2.setMaximum(100)
        self.horizontalSliderBicepsG2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBicepsG2.setObjectName("horizontalSliderBicepsG2")
        self.horizontalLayout.addWidget(self.horizontalSliderBicepsG2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalSliderBicepsD0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderBicepsD0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderBicepsD0.setMinimum(0)
        self.horizontalSliderBicepsD0.setMaximum(100)
        self.horizontalSliderBicepsD0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBicepsD0.setObjectName("horizontalSliderBicepsD0")
        self.horizontalLayout_5.addWidget(self.horizontalSliderBicepsD0)
        self.horizontalSliderBicepsD2 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderBicepsD2.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderBicepsD2.setMinimum(0)
        self.horizontalSliderBicepsD2.setMaximum(100)
        self.horizontalSliderBicepsD2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBicepsD2.setObjectName("horizontalSliderBicepsD2")
        self.horizontalLayout_5.addWidget(self.horizontalSliderBicepsD2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.pushButtonCoudeG = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonCoudeG.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonCoudeG.setObjectName("pushButtonCoudeG")
        self.gridLayout_2.addWidget(self.pushButtonCoudeG, 7, 0, 1, 1)
        self.pushButtonCoudeD = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonCoudeD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonCoudeD.setObjectName("pushButtonCoudeD")
        self.gridLayout_2.addWidget(self.pushButtonCoudeD, 7, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSliderCoudeG1 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderCoudeG1.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderCoudeG1.setMinimum(0)
        self.horizontalSliderCoudeG1.setMaximum(100)
        self.horizontalSliderCoudeG1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCoudeG1.setObjectName("horizontalSliderCoudeG1")
        self.horizontalLayout_4.addWidget(self.horizontalSliderCoudeG1)
        self.horizontalSliderCoudeG0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderCoudeG0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderCoudeG0.setMinimum(0)
        self.horizontalSliderCoudeG0.setMaximum(100)
        self.horizontalSliderCoudeG0.setProperty("value", 0)
        self.horizontalSliderCoudeG0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCoudeG0.setObjectName("horizontalSliderCoudeG0")
        self.horizontalLayout_4.addWidget(self.horizontalSliderCoudeG0)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
        self.pushButtonMainG = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonMainG.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonMainG.setObjectName("pushButtonMainG")
        self.gridLayout_2.addWidget(self.pushButtonMainG, 10, 0, 1, 1)
        self.pushButtonMainD = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonMainD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonMainD.setObjectName("pushButtonMainD")
        self.gridLayout_2.addWidget(self.pushButtonMainD, 10, 1, 1, 1)
        self.horizontalSliderMainG1 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderMainG1.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderMainG1.setMinimum(0)
        self.horizontalSliderMainG1.setMaximum(100)
        self.horizontalSliderMainG1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMainG1.setObjectName("horizontalSliderMainG1")
        self.gridLayout_2.addWidget(self.horizontalSliderMainG1, 12, 0, 1, 1)
        self.horizontalSliderMainD1 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderMainD1.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderMainD1.setMinimum(0)
        self.horizontalSliderMainD1.setMaximum(100)
        self.horizontalSliderMainD1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMainD1.setObjectName("horizontalSliderMainD1")
        self.gridLayout_2.addWidget(self.horizontalSliderMainD1, 12, 1, 1, 1)
        self.pushButtonDoigtsG = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonDoigtsG.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonDoigtsG.setObjectName("pushButtonDoigtsG")
        self.gridLayout_2.addWidget(self.pushButtonDoigtsG, 13, 0, 1, 1)
        self.pushButtonDoigtsD = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonDoigtsD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonDoigtsD.setObjectName("pushButtonDoigtsD")
        self.gridLayout_2.addWidget(self.pushButtonDoigtsD, 13, 1, 1, 1)
        self.horizontalSliderDoigtsG0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderDoigtsG0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderDoigtsG0.setMaximum(100)
        self.horizontalSliderDoigtsG0.setSingleStep(10)
        self.horizontalSliderDoigtsG0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDoigtsG0.setObjectName("horizontalSliderDoigtsG0")
        self.gridLayout_2.addWidget(self.horizontalSliderDoigtsG0, 14, 0, 1, 1)
        self.horizontalSliderDoigtsD0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderDoigtsD0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderDoigtsD0.setMaximum(100)
        self.horizontalSliderDoigtsD0.setSingleStep(10)
        self.horizontalSliderDoigtsD0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDoigtsD0.setObjectName("horizontalSliderDoigtsD0")
        self.gridLayout_2.addWidget(self.horizontalSliderDoigtsD0, 14, 1, 1, 1)
        self.horizontalSliderTete2 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderTete2.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderTete2.setMinimum(0)
        self.horizontalSliderTete2.setMaximum(100)
        self.horizontalSliderTete2.setProperty("value", 0)
        self.horizontalSliderTete2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTete2.setObjectName("horizontalSliderTete2")
        self.gridLayout_2.addWidget(self.horizontalSliderTete2, 3, 0, 1, 1)
        self.horizontalSliderTete0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderTete0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderTete0.setMinimum(0)
        self.horizontalSliderTete0.setMaximum(100)
        self.horizontalSliderTete0.setProperty("value", 0)
        self.horizontalSliderTete0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTete0.setObjectName("horizontalSliderTete0")
        self.gridLayout_2.addWidget(self.horizontalSliderTete0, 3, 1, 1, 1)
        self.pushButtonTeteHB = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonTeteHB.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonTeteHB.setAcceptDrops(True)
        self.pushButtonTeteHB.setObjectName("pushButtonTeteHB")
        self.gridLayout_2.addWidget(self.pushButtonTeteHB, 2, 1, 1, 1)
        self.pushButtonTeteGD = QtGui.QPushButton(self.widgetButtonContainer)
        self.pushButtonTeteGD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonTeteGD.setObjectName("pushButtonTeteGD")
        self.gridLayout_2.addWidget(self.pushButtonTeteGD, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalSliderCoudeD1 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderCoudeD1.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderCoudeD1.setMinimum(0)
        self.horizontalSliderCoudeD1.setMaximum(100)
        self.horizontalSliderCoudeD1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCoudeD1.setObjectName("horizontalSliderCoudeD1")
        self.horizontalLayout_7.addWidget(self.horizontalSliderCoudeD1)
        self.horizontalSliderCoudeD0 = QtGui.QSlider(self.widgetButtonContainer)
        self.horizontalSliderCoudeD0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderCoudeD0.setMinimum(0)
        self.horizontalSliderCoudeD0.setMaximum(100)
        self.horizontalSliderCoudeD0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCoudeD0.setObjectName("horizontalSliderCoudeD0")
        self.horizontalLayout_7.addWidget(self.horizontalSliderCoudeD0)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 8, 1, 1, 1)
        self.gridLayout.addWidget(self.widgetButtonContainer, 0, 0, 1, 1)
        self.tabWidget2.addTab(self.tab1, "")
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtGui.QLabel(self.tab2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setContentsMargins(100, -1, 100, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButtonHanche = QtGui.QPushButton(self.tab2)
        self.pushButtonHanche.setObjectName("pushButtonHanche")
        self.verticalLayout_7.addWidget(self.pushButtonHanche)
        self.horizontalSliderHanche15 = QtGui.QSlider(self.tab2)
        self.horizontalSliderHanche15.setMinimum(0)
        self.horizontalSliderHanche15.setMaximum(100)
        self.horizontalSliderHanche15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderHanche15.setObjectName("horizontalSliderHanche15")
        self.verticalLayout_7.addWidget(self.horizontalSliderHanche15)
        self.verticalLayout_14.addLayout(self.verticalLayout_7)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButtonCuisseG = QtGui.QPushButton(self.tab2)
        self.pushButtonCuisseG.setObjectName("pushButtonCuisseG")
        self.verticalLayout_9.addWidget(self.pushButtonCuisseG)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalSliderCuisseG0 = QtGui.QSlider(self.tab2)
        self.horizontalSliderCuisseG0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderCuisseG0.setMinimum(0)
        self.horizontalSliderCuisseG0.setMaximum(100)
        self.horizontalSliderCuisseG0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCuisseG0.setObjectName("horizontalSliderCuisseG0")
        self.horizontalLayout_25.addWidget(self.horizontalSliderCuisseG0)
        self.horizontalSliderCuisseG1 = QtGui.QSlider(self.tab2)
        self.horizontalSliderCuisseG1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCuisseG1.setObjectName("horizontalSliderCuisseG1")
        self.horizontalLayout_25.addWidget(self.horizontalSliderCuisseG1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_22.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButtonCuisseD = QtGui.QPushButton(self.tab2)
        self.pushButtonCuisseD.setObjectName("pushButtonCuisseD")
        self.verticalLayout_8.addWidget(self.pushButtonCuisseD)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalSliderCuisseD0 = QtGui.QSlider(self.tab2)
        self.horizontalSliderCuisseD0.setMinimum(0)
        self.horizontalSliderCuisseD0.setMaximum(100)
        self.horizontalSliderCuisseD0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCuisseD0.setObjectName("horizontalSliderCuisseD0")
        self.horizontalLayout_26.addWidget(self.horizontalSliderCuisseD0)
        self.horizontalSliderCuisseD1 = QtGui.QSlider(self.tab2)
        self.horizontalSliderCuisseD1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCuisseD1.setObjectName("horizontalSliderCuisseD1")
        self.horizontalLayout_26.addWidget(self.horizontalSliderCuisseD1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_22.addLayout(self.verticalLayout_8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButtonMolletG = QtGui.QPushButton(self.tab2)
        self.pushButtonMolletG.setObjectName("pushButtonMolletG")
        self.verticalLayout_10.addWidget(self.pushButtonMolletG)
        self.horizontalSliderMolletG0 = QtGui.QSlider(self.tab2)
        self.horizontalSliderMolletG0.setMaximum(100)
        self.horizontalSliderMolletG0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMolletG0.setObjectName("horizontalSliderMolletG0")
        self.verticalLayout_10.addWidget(self.horizontalSliderMolletG0)
        self.horizontalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButtonMolletD = QtGui.QPushButton(self.tab2)
        self.pushButtonMolletD.setObjectName("pushButtonMolletD")
        self.verticalLayout_11.addWidget(self.pushButtonMolletD)
        self.horizontalSliderMolletD0 = QtGui.QSlider(self.tab2)
        self.horizontalSliderMolletD0.setMaximum(100)
        self.horizontalSliderMolletD0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMolletD0.setObjectName("horizontalSliderMolletD0")
        self.verticalLayout_11.addWidget(self.horizontalSliderMolletD0)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButtonPiedG = QtGui.QPushButton(self.tab2)
        self.pushButtonPiedG.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonPiedG.setObjectName("pushButtonPiedG")
        self.verticalLayout_13.addWidget(self.pushButtonPiedG)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalSliderPiedG0 = QtGui.QSlider(self.tab2)
        self.horizontalSliderPiedG0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderPiedG0.setMinimum(0)
        self.horizontalSliderPiedG0.setMaximum(100)
        self.horizontalSliderPiedG0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPiedG0.setObjectName("horizontalSliderPiedG0")
        self.horizontalLayout_6.addWidget(self.horizontalSliderPiedG0)
        self.horizontalSliderPiedG1 = QtGui.QSlider(self.tab2)
        self.horizontalSliderPiedG1.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderPiedG1.setMinimum(0)
        self.horizontalSliderPiedG1.setMaximum(100)
        self.horizontalSliderPiedG1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPiedG1.setObjectName("horizontalSliderPiedG1")
        self.horizontalLayout_6.addWidget(self.horizontalSliderPiedG1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButtonPiedD = QtGui.QPushButton(self.tab2)
        self.pushButtonPiedD.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButtonPiedD.setObjectName("pushButtonPiedD")
        self.verticalLayout_12.addWidget(self.pushButtonPiedD)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalSliderPiedD0 = QtGui.QSlider(self.tab2)
        self.horizontalSliderPiedD0.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderPiedD0.setMinimum(0)
        self.horizontalSliderPiedD0.setMaximum(100)
        self.horizontalSliderPiedD0.setProperty("value", 0)
        self.horizontalSliderPiedD0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPiedD0.setObjectName("horizontalSliderPiedD0")
        self.horizontalLayout_8.addWidget(self.horizontalSliderPiedD0)
        self.horizontalSliderPiedD1 = QtGui.QSlider(self.tab2)
        self.horizontalSliderPiedD1.setMaximumSize(QtCore.QSize(16777215, 18))
        self.horizontalSliderPiedD1.setMinimum(0)
        self.horizontalSliderPiedD1.setMaximum(100)
        self.horizontalSliderPiedD1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPiedD1.setObjectName("horizontalSliderPiedD1")
        self.horizontalLayout_8.addWidget(self.horizontalSliderPiedD1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.tabWidget2.addTab(self.tab2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setMinimumSize(QtCore.QSize(200, 0))
        self.label_17.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.checkBoxSelectAll = QtGui.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.checkBoxSelectAll.setFont(font)
        self.checkBoxSelectAll.setObjectName("checkBoxSelectAll")
        self.verticalLayout_5.addWidget(self.checkBoxSelectAll)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxCoteGauche = QtGui.QCheckBox(self.tab)
        self.checkBoxCoteGauche.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxCoteGauche.setFont(font)
        self.checkBoxCoteGauche.setObjectName("checkBoxCoteGauche")
        self.horizontalLayout_3.addWidget(self.checkBoxCoteGauche)
        self.line = QtGui.QFrame(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.checkBoxCoteDroit = QtGui.QCheckBox(self.tab)
        self.checkBoxCoteDroit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxCoteDroit.setFont(font)
        self.checkBoxCoteDroit.setObjectName("checkBoxCoteDroit")
        self.horizontalLayout_3.addWidget(self.checkBoxCoteDroit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.checkBoxLed1 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed1.setFont(font)
        self.checkBoxLed1.setObjectName("checkBoxLed1")
        self.horizontalLayout_20.addWidget(self.checkBoxLed1)
        self.checkBoxLed2 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed2.setFont(font)
        self.checkBoxLed2.setObjectName("checkBoxLed2")
        self.horizontalLayout_20.addWidget(self.checkBoxLed2)
        self.checkBoxLed3 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed3.setFont(font)
        self.checkBoxLed3.setObjectName("checkBoxLed3")
        self.horizontalLayout_20.addWidget(self.checkBoxLed3)
        self.checkBoxLed4 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed4.setFont(font)
        self.checkBoxLed4.setObjectName("checkBoxLed4")
        self.horizontalLayout_20.addWidget(self.checkBoxLed4)
        self.checkBoxLed5 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed5.setFont(font)
        self.checkBoxLed5.setObjectName("checkBoxLed5")
        self.horizontalLayout_20.addWidget(self.checkBoxLed5)
        self.checkBoxLed6 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed6.setFont(font)
        self.checkBoxLed6.setObjectName("checkBoxLed6")
        self.horizontalLayout_20.addWidget(self.checkBoxLed6)
        self.checkBoxLed7 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed7.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed7.setFont(font)
        self.checkBoxLed7.setObjectName("checkBoxLed7")
        self.horizontalLayout_20.addWidget(self.checkBoxLed7)
        self.checkBoxLed8 = QtGui.QCheckBox(self.tab)
        self.checkBoxLed8.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxLed8.setFont(font)
        self.checkBoxLed8.setObjectName("checkBoxLed8")
        self.horizontalLayout_20.addWidget(self.checkBoxLed8)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setMinimumSize(QtCore.QSize(10, 0))
        self.label_21.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spinBoxRouge = QtGui.QSpinBox(self.tab)
        self.spinBoxRouge.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBoxRouge.setMaximum(255)
        self.spinBoxRouge.setObjectName("spinBoxRouge")
        self.horizontalLayout_11.addWidget(self.spinBoxRouge)
        self.verticalLayout_15.addLayout(self.horizontalLayout_11)
        self.horizontalSliderRouge = QtGui.QSlider(self.tab)
        self.horizontalSliderRouge.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalSliderRouge.setMinimum(0)
        self.horizontalSliderRouge.setMaximum(255)
        self.horizontalSliderRouge.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRouge.setObjectName("horizontalSliderRouge")
        self.verticalLayout_15.addWidget(self.horizontalSliderRouge)
        self.horizontalLayout_13.addLayout(self.verticalLayout_15)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.spinBoxVert = QtGui.QSpinBox(self.tab)
        self.spinBoxVert.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBoxVert.setMaximum(255)
        self.spinBoxVert.setObjectName("spinBoxVert")
        self.horizontalLayout_14.addWidget(self.spinBoxVert)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalSliderVert = QtGui.QSlider(self.tab)
        self.horizontalSliderVert.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalSliderVert.setMinimum(0)
        self.horizontalSliderVert.setMaximum(255)
        self.horizontalSliderVert.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderVert.setObjectName("horizontalSliderVert")
        self.verticalLayout_4.addWidget(self.horizontalSliderVert)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_24.addWidget(self.label_23)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.spinBoxBleu = QtGui.QSpinBox(self.tab)
        self.spinBoxBleu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBoxBleu.setMaximum(255)
        self.spinBoxBleu.setObjectName("spinBoxBleu")
        self.horizontalLayout_15.addWidget(self.spinBoxBleu)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalSliderBleu = QtGui.QSlider(self.tab)
        self.horizontalSliderBleu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.horizontalSliderBleu.setMinimum(0)
        self.horizontalSliderBleu.setMaximum(255)
        self.horizontalSliderBleu.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBleu.setObjectName("horizontalSliderBleu")
        self.verticalLayout_2.addWidget(self.horizontalSliderBleu)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButtonChangeColors = QtGui.QPushButton(self.tab)
        self.pushButtonChangeColors.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonChangeColors.setObjectName("pushButtonChangeColors")
        self.horizontalLayout_18.addWidget(self.pushButtonChangeColors)
        self.pushButtonStopLights = QtGui.QPushButton(self.tab)
        self.pushButtonStopLights.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonStopLights.setObjectName("pushButtonStopLights")
        self.horizontalLayout_18.addWidget(self.pushButtonStopLights)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.tabWidget2.addTab(self.tab, "")
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtGui.QLabel(self.tab3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 1, 1, 1)
        self.pushButtonTeteDessus = QtGui.QPushButton(self.tab3)
        self.pushButtonTeteDessus.setObjectName("pushButtonTeteDessus")
        self.gridLayout_4.addWidget(self.pushButtonTeteDessus, 7, 1, 1, 1)
        self.pushButtonTeteDevant = QtGui.QPushButton(self.tab3)
        self.pushButtonTeteDevant.setObjectName("pushButtonTeteDevant")
        self.gridLayout_4.addWidget(self.pushButtonTeteDevant, 7, 0, 1, 1)
        self.pushButtonTeteArriere = QtGui.QPushButton(self.tab3)
        self.pushButtonTeteArriere.setObjectName("pushButtonTeteArriere")
        self.gridLayout_4.addWidget(self.pushButtonTeteArriere, 7, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab3)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 1, 1, 1)
        self.pushButtonMainDDevant = QtGui.QPushButton(self.tab3)
        self.pushButtonMainDDevant.setObjectName("pushButtonMainDDevant")
        self.gridLayout_4.addWidget(self.pushButtonMainDDevant, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 1, 1, 1)
        self.pushButtonMainDArriere = QtGui.QPushButton(self.tab3)
        self.pushButtonMainDArriere.setObjectName("pushButtonMainDArriere")
        self.gridLayout_4.addWidget(self.pushButtonMainDArriere, 3, 2, 1, 1)
        self.pushButtonMainDDessus = QtGui.QPushButton(self.tab3)
        self.pushButtonMainDDessus.setObjectName("pushButtonMainDDessus")
        self.gridLayout_4.addWidget(self.pushButtonMainDDessus, 3, 1, 1, 1)
        self.pushButtonMainGDessus = QtGui.QPushButton(self.tab3)
        self.pushButtonMainGDessus.setObjectName("pushButtonMainGDessus")
        self.gridLayout_4.addWidget(self.pushButtonMainGDessus, 5, 1, 1, 1)
        self.pushButtonMainGDevant = QtGui.QPushButton(self.tab3)
        self.pushButtonMainGDevant.setObjectName("pushButtonMainGDevant")
        self.gridLayout_4.addWidget(self.pushButtonMainGDevant, 5, 0, 1, 1)
        self.pushButtonMainGArriere = QtGui.QPushButton(self.tab3)
        self.pushButtonMainGArriere.setObjectName("pushButtonMainGArriere")
        self.gridLayout_4.addWidget(self.pushButtonMainGArriere, 5, 2, 1, 1)
        self.tabWidget2.addTab(self.tab3, "")
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName("tab4")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEditSpeak = QtGui.QLineEdit(self.tab4)
        self.lineEditSpeak.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEditSpeak.setObjectName("lineEditSpeak")
        self.gridLayout_5.addWidget(self.lineEditSpeak, 1, 0, 1, 1)
        self.labelParler = QtGui.QLabel(self.tab4)
        self.labelParler.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelParler.setFont(font)
        self.labelParler.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParler.setObjectName("labelParler")
        self.gridLayout_5.addWidget(self.labelParler, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButtonValidSpeak = QtGui.QPushButton(self.tab4)
        self.pushButtonValidSpeak.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonValidSpeak.setObjectName("pushButtonValidSpeak")
        self.horizontalLayout_17.addWidget(self.pushButtonValidSpeak)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBox = QtGui.QComboBox(self.tab4)
        self.comboBox.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.pushButtonReconnaitre = QtGui.QPushButton(self.tab4)
        self.pushButtonReconnaitre.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonReconnaitre.setObjectName("pushButtonReconnaitre")
        self.horizontalLayout_9.addWidget(self.pushButtonReconnaitre)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEditObjet = QtGui.QLineEdit(self.tab4)
        self.lineEditObjet.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditObjet.setObjectName("lineEditObjet")
        self.horizontalLayout_10.addWidget(self.lineEditObjet)
        self.pushButtonObjet = QtGui.QPushButton(self.tab4)
        self.pushButtonObjet.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonObjet.setObjectName("pushButtonObjet")
        self.horizontalLayout_10.addWidget(self.pushButtonObjet)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget2.addTab(self.tab4, "")
        self.horizontalLayout_23.addWidget(self.tabWidget2)
        self.tabWidget.addTab(self.tabPupitre, "")
        self.tabConsole = QtGui.QWidget()
        self.tabConsole.setObjectName("tabConsole")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabConsole)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetShellContainer = QtGui.QWidget(self.tabConsole)
        self.widgetShellContainer.setObjectName("widgetShellContainer")
        self.verticalLayout_3.addWidget(self.widgetShellContainer)
        self.tabWidget.addTab(self.tabConsole, "")
        self.verticalLayout.addWidget(self.splitterHB)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBarNaoSimulator = QtGui.QMenuBar(MainWindow)
        self.menuBarNaoSimulator.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menuBarNaoSimulator.setObjectName("menuBarNaoSimulator")
        self.menuFichier = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuFichier.setObjectName("menuFichier")
        self.menuEdition = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuEdition.setObjectName("menuEdition")
        self.menuFormat = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuFormat.setObjectName("menuFormat")
        self.menuAide = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuAide.setObjectName("menuAide")
        self.menuRobot = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuRobot.setObjectName("menuRobot")
        self.menuCouleur = QtGui.QMenu(self.menuRobot)
        self.menuCouleur.setObjectName("menuCouleur")
        self.menuAffichage = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuAffichage.setObjectName("menuAffichage")
        self.menuShell = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuShell.setObjectName("menuShell")
        self.menuConnexion = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuConnexion.setObjectName("menuConnexion")
        self.menuRun = QtGui.QMenu(self.menuBarNaoSimulator)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menuBarNaoSimulator)
        self.toolBarNaoSimulator = QtGui.QToolBar(MainWindow)
        self.toolBarNaoSimulator.setCursor(QtCore.Qt.PointingHandCursor)
        self.toolBarNaoSimulator.setObjectName("toolBarNaoSimulator")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarNaoSimulator)
        self.actionOuvrir = QtGui.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionEnregistrer = QtGui.QAction(MainWindow)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionCouper = QtGui.QAction(MainWindow)
        self.actionCouper.setObjectName("actionCouper")
        self.actionCopier = QtGui.QAction(MainWindow)
        self.actionCopier.setObjectName("actionCopier")
        self.actionColler = QtGui.QAction(MainWindow)
        self.actionColler.setObjectName("actionColler")
        self.actionCommenter = QtGui.QAction(MainWindow)
        self.actionCommenter.setObjectName("actionCommenter")
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionApropos = QtGui.QAction(MainWindow)
        self.actionApropos.setObjectName("actionApropos")
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/fleche.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon1)
        self.actionRun.setObjectName("actionRun")
        self.actionPause = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon2)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/arret.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName("actionStop")
        self.actionNaoT14 = QtGui.QAction(MainWindow)
        self.actionNaoT14.setObjectName("actionNaoT14")
        self.actionNaoH25 = QtGui.QAction(MainWindow)
        self.actionNaoH25.setObjectName("actionNaoH25")
        self.actionReinitialiser_Pupitre = QtGui.QAction(MainWindow)
        self.actionReinitialiser_Pupitre.setObjectName("actionReinitialiser_Pupitre")
        self.actionReinitialiser_Editeur = QtGui.QAction(MainWindow)
        self.actionReinitialiser_Editeur.setObjectName("actionReinitialiser_Editeur")
        self.actionReinitialiser_Vue_3D = QtGui.QAction(MainWindow)
        self.actionReinitialiser_Vue_3D.setObjectName("actionReinitialiser_Vue_3D")
        self.actionOrange = QtGui.QAction(MainWindow)
        self.actionOrange.setCheckable(True)
        self.actionOrange.setChecked(True)
        self.actionOrange.setObjectName("actionOrange")
        self.actionGris = QtGui.QAction(MainWindow)
        self.actionGris.setCheckable(True)
        self.actionGris.setObjectName("actionGris")
        self.actionBleu = QtGui.QAction(MainWindow)
        self.actionBleu.setCheckable(True)
        self.actionBleu.setObjectName("actionBleu")
        self.actionNoir = QtGui.QAction(MainWindow)
        self.actionNoir.setCheckable(True)
        self.actionNoir.setObjectName("actionNoir")
        self.actionAnnuler = QtGui.QAction(MainWindow)
        self.actionAnnuler.setObjectName("actionAnnuler")
        self.actionRetablir = QtGui.QAction(MainWindow)
        self.actionRetablir.setObjectName("actionRetablir")
        self.actionDecommenter = QtGui.QAction(MainWindow)
        self.actionDecommenter.setObjectName("actionDecommenter")
        self.actionSupprimer = QtGui.QAction(MainWindow)
        self.actionSupprimer.setObjectName("actionSupprimer")
        self.actionEnregistrer_sous = QtGui.QAction(MainWindow)
        self.actionEnregistrer_sous.setObjectName("actionEnregistrer_sous")
        self.actionEffacer = QtGui.QAction(MainWindow)
        self.actionEffacer.setObjectName("actionEffacer")
        self.actionRunReal = QtGui.QAction(MainWindow)
        self.actionRunReal.setCheckable(True)
        self.actionRunReal.setObjectName("actionRunReal")
        self.actionRun_2 = QtGui.QAction(MainWindow)
        self.actionRun_2.setObjectName("actionRun_2")
        self.actionStop_2 = QtGui.QAction(MainWindow)
        self.actionStop_2.setObjectName("actionStop_2")
        self.actionInitPosition = QtGui.QAction(MainWindow)
        self.actionInitPosition.setObjectName("actionInitPosition")
        self.actionConfiguration = QtGui.QAction(MainWindow)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionNaoH21 = QtGui.QAction(MainWindow)
        self.actionNaoH21.setObjectName("actionNaoH21")
        self.actionColors = QtGui.QAction(MainWindow)
        self.actionColors.setObjectName("actionColors")
        self.actionRelancer = QtGui.QAction(MainWindow)
        self.actionRelancer.setObjectName("actionRelancer")
        self.actionIndenter = QtGui.QAction(MainWindow)
        self.actionIndenter.setObjectName("actionIndenter")
        self.actionDedenter = QtGui.QAction(MainWindow)
        self.actionDedenter.setObjectName("actionDedenter")
        self.actionAfficherPosition = QtGui.QAction(MainWindow)
        self.actionAfficherPosition.setObjectName("actionAfficherPosition")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionEnregistrer_sous)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionRelancer)
        self.menuFichier.addAction(self.actionQuitter)
        self.menuEdition.addAction(self.actionAnnuler)
        self.menuEdition.addAction(self.actionRetablir)
        self.menuEdition.addSeparator()
        self.menuEdition.addAction(self.actionCouper)
        self.menuEdition.addAction(self.actionCopier)
        self.menuEdition.addAction(self.actionColler)
        self.menuFormat.addAction(self.actionCommenter)
        self.menuFormat.addAction(self.actionDecommenter)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionIndenter)
        self.menuFormat.addAction(self.actionDedenter)
        self.menuAide.addAction(self.actionDocumentation)
        self.menuAide.addAction(self.actionApropos)
        self.menuCouleur.addAction(self.actionOrange)
        self.menuCouleur.addAction(self.actionGris)
        self.menuCouleur.addAction(self.actionBleu)
        self.menuCouleur.addAction(self.actionNoir)
        self.menuRobot.addAction(self.actionNaoT14)
        self.menuRobot.addAction(self.actionNaoH21)
        self.menuRobot.addAction(self.actionNaoH25)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.menuCouleur.menuAction())
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionAfficherPosition)
        self.menuRobot.addAction(self.actionInitPosition)
        self.menuAffichage.addAction(self.actionColors)
        self.menuAffichage.addSeparator()
        self.menuAffichage.addAction(self.actionReinitialiser_Pupitre)
        self.menuAffichage.addAction(self.actionReinitialiser_Editeur)
        self.menuAffichage.addAction(self.actionReinitialiser_Vue_3D)
        self.menuShell.addAction(self.actionEffacer)
        self.menuConnexion.addAction(self.actionRunReal)
        self.menuConnexion.addAction(self.actionConfiguration)
        self.menuRun.addAction(self.actionRun_2)
        self.menuRun.addAction(self.actionStop_2)
        self.menuBarNaoSimulator.addAction(self.menuFichier.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuEdition.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuFormat.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuRun.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuConnexion.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuShell.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuRobot.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuAffichage.menuAction())
        self.menuBarNaoSimulator.addAction(self.menuAide.menuAction())
        self.toolBarNaoSimulator.addAction(self.actionRun)
        self.toolBarNaoSimulator.addAction(self.actionStop)
        self.toolBarNaoSimulator.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NAO Simulator 2014", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">from time import sleep</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">from NaoVirtual import Nao</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">from NaoCommunication import NaoControle</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">nao=NaoControle(Nao())</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">for a in range(16):</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">    nao.allumerLed(a)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">    sleep(0.5)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">for a in range(15,-1,-1):</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">    nao.eteindreLed(a)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">    sleep(0.2)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Ordres</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBicepsG.setText(QtGui.QApplication.translate("MainWindow", "Biceps Gauche (XX : H/B ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBicepsD.setText(QtGui.QApplication.translate("MainWindow", "Biceps Droit (XX : H/B ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCoudeG.setText(QtGui.QApplication.translate("MainWindow", "Coude Gauche (XX : Z ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCoudeD.setText(QtGui.QApplication.translate("MainWindow", "Coude Droit (XX : Z ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainG.setText(QtGui.QApplication.translate("MainWindow", "XX : Rotation Main Gauche", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainD.setText(QtGui.QApplication.translate("MainWindow", "XX : Rotation Main Droite", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDoigtsG.setText(QtGui.QApplication.translate("MainWindow", "XX : Doigts Gauches", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDoigtsD.setText(QtGui.QApplication.translate("MainWindow", "XX : Doigts Droits", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTeteHB.setText(QtGui.QApplication.translate("MainWindow", "XX : Tête H/B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTeteGD.setText(QtGui.QApplication.translate("MainWindow", "XX : Tête G/D", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "Haut du corps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Ordres</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHanche.setText(QtGui.QApplication.translate("MainWindow", "XX : Hanche (GH/BD)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCuisseG.setText(QtGui.QApplication.translate("MainWindow", "Cuisse Gauche (XX : H/B ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCuisseD.setText(QtGui.QApplication.translate("MainWindow", "Cuisse Droite (XX : H/B ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMolletG.setText(QtGui.QApplication.translate("MainWindow", "XX : Mollet Gauche", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMolletD.setText(QtGui.QApplication.translate("MainWindow", "XX : Mollet Droit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPiedG.setText(QtGui.QApplication.translate("MainWindow", "Pied Gauche (XX : H/B ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPiedD.setText(QtGui.QApplication.translate("MainWindow", "Pied Droit (XX : H/B ; YY : G/D)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Bas du corps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Coloration des LED", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSelectAll.setText(QtGui.QApplication.translate("MainWindow", "Tout sélectionner", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCoteGauche.setText(QtGui.QApplication.translate("MainWindow", "Gauche", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCoteDroit.setText(QtGui.QApplication.translate("MainWindow", "Droite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "LED n°", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLed8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Composantes de la couleur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Rouge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Vert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Bleu", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChangeColors.setText(QtGui.QApplication.translate("MainWindow", "Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStopLights.setText(QtGui.QApplication.translate("MainWindow", "Éteindre", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Lumières", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Capteurs</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Tête</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTeteDessus.setText(QtGui.QApplication.translate("MainWindow", "7 : Dessus", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTeteDevant.setText(QtGui.QApplication.translate("MainWindow", "6 : Devant", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTeteArriere.setText(QtGui.QApplication.translate("MainWindow", "8 : Arrière", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Main Droite</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainDDevant.setText(QtGui.QApplication.translate("MainWindow", "0 : Devant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Main Gauche</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainDArriere.setText(QtGui.QApplication.translate("MainWindow", "2 : Arrière", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainDDessus.setText(QtGui.QApplication.translate("MainWindow", "1 : Dessus", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainGDessus.setText(QtGui.QApplication.translate("MainWindow", "4 : Dessus", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainGDevant.setText(QtGui.QApplication.translate("MainWindow", "3 : Devant", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMainGArriere.setText(QtGui.QApplication.translate("MainWindow", "5 : Arrière", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab3), QtGui.QApplication.translate("MainWindow", "Capteurs", None, QtGui.QApplication.UnicodeUTF8))
        self.labelParler.setText(QtGui.QApplication.translate("MainWindow", "Parler au robot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonValidSpeak.setText(QtGui.QApplication.translate("MainWindow", "Parler", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Faire reconnaitre un visage ou un objet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Faire enregistrer un visage ou un objet", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonReconnaitre.setText(QtGui.QApplication.translate("MainWindow", "Reconnaitre", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonObjet.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.tab4), QtGui.QApplication.translate("MainWindow", "Simulateur d\'évènements", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPupitre), QtGui.QApplication.translate("MainWindow", "Pupitre", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConsole), QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdition.setTitle(QtGui.QApplication.translate("MainWindow", "Édition", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFormat.setTitle(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("MainWindow", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRobot.setTitle(QtGui.QApplication.translate("MainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCouleur.setTitle(QtGui.QApplication.translate("MainWindow", "Couleur", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAffichage.setTitle(QtGui.QApplication.translate("MainWindow", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShell.setTitle(QtGui.QApplication.translate("MainWindow", "Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConnexion.setTitle(QtGui.QApplication.translate("MainWindow", "Connexion", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNaoSimulator.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOuvrir.setText(QtGui.QApplication.translate("MainWindow", "Ouvrir...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOuvrir.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCouper.setText(QtGui.QApplication.translate("MainWindow", "Couper", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCouper.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopier.setText(QtGui.QApplication.translate("MainWindow", "Copier", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopier.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColler.setText(QtGui.QApplication.translate("MainWindow", "Coller", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColler.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommenter.setText(QtGui.QApplication.translate("MainWindow", "Commenter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommenter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionApropos.setText(QtGui.QApplication.translate("MainWindow", "À propos...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNaoT14.setText(QtGui.QApplication.translate("MainWindow", "NAO T14", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNaoT14.setToolTip(QtGui.QApplication.translate("MainWindow", "NaoT14", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNaoH25.setText(QtGui.QApplication.translate("MainWindow", "NAO H25", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNaoH25.setToolTip(QtGui.QApplication.translate("MainWindow", "NaoH25", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReinitialiser_Pupitre.setText(QtGui.QApplication.translate("MainWindow", "Réinitialiser Pupitre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReinitialiser_Editeur.setText(QtGui.QApplication.translate("MainWindow", "Réinitialiser Éditeur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReinitialiser_Vue_3D.setText(QtGui.QApplication.translate("MainWindow", "Réinitialiser Vue 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrange.setText(QtGui.QApplication.translate("MainWindow", "Orange", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGris.setText(QtGui.QApplication.translate("MainWindow", "Gris", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBleu.setText(QtGui.QApplication.translate("MainWindow", "Bleu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNoir.setText(QtGui.QApplication.translate("MainWindow", "Noir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnnuler.setText(QtGui.QApplication.translate("MainWindow", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnnuler.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRetablir.setText(QtGui.QApplication.translate("MainWindow", "Rétablir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRetablir.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecommenter.setText(QtGui.QApplication.translate("MainWindow", "Décommenter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecommenter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSupprimer.setText(QtGui.QApplication.translate("MainWindow", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer_sous.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer sous...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer_sous.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEffacer.setText(QtGui.QApplication.translate("MainWindow", "Effacer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRunReal.setText(QtGui.QApplication.translate("MainWindow", "Exécuter sur NAO réel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRunReal.setToolTip(QtGui.QApplication.translate("MainWindow", "Si coché, le programme que vous avez écrit sera lancé sur le vrai robot connecté et sur celui du simulateur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_2.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_2.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_2.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_2.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInitPosition.setText(QtGui.QApplication.translate("MainWindow", "Réinitialiser Position", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguration.setText(QtGui.QApplication.translate("MainWindow", "Configuration...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNaoH21.setText(QtGui.QApplication.translate("MainWindow", "NAO H21", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColors.setText(QtGui.QApplication.translate("MainWindow", "Personnaliser les couleurs...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRelancer.setText(QtGui.QApplication.translate("MainWindow", "Relancer (Python 2.7.4+)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIndenter.setText(QtGui.QApplication.translate("MainWindow", "Augmenter l\'indentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDedenter.setText(QtGui.QApplication.translate("MainWindow", "Réduire l\'indentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfficherPosition.setText(QtGui.QApplication.translate("MainWindow", "Afficher Position", None, QtGui.QApplication.UnicodeUTF8))

import rsc_rc
